version: '2.2'

services:
  magento2_application:
    image: tianon/true
    volumes:
      - ./code:/var/www/html

  magento2_nginx:
#    see link: https://web.docker.pp.ua/?page=1#!taglist/magento2-nginx
    image: docker.pp.ua/magento2-nginx:latest
#    build: ./builds-custom/nginx
    links:
      - magento2_php
    depends_on:
      - magento2_php
      - magento2_application
    volumes_from:
      - magento2_application
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./config/nginx/subdomain.conf:/etc/nginx/conf.d/subdomain.template
      - ./config/nginx/subdomains:/etc/nginx/conf.d/subdomains:rw
      - ./ssl:/etc/nginx/cert
    env_file:
      - ./env/nginx.env
    environment:
      - VIRTUAL_HOST=magento2.dev
      - MAGE_MODE=developer
      - MAGE_RUN_CODE=default
      - MAGE_RUN_TYPE=store
      - DOMAINS=magento2.local=default magento2.test=default
    command: /bin/bash -c "/usr/local/bin/docker-entrypoint.sh && exec nginx -g 'daemon off;'"
    expose:
      - 80
    ports:
      - 80:80
      - 443:443

  magento2_php:
#    see link: https://web.docker.pp.ua/#!taglist/magento2-php
    image: docker.pp.ua/magento2-php:latest
#    build: ./builds-custom/php
    container_name: magento2_php
    links:
      - magento2_mysql
    depends_on:
      - magento2_mysql
      - magento2_application
      - magento2_mailhog
      - magento2_redis
      - magento2_elasticsearch
    volumes_from:
      - magento2_application
    volumes:
      - ./config/composer/auth.json:/var/www/.composer/auth.json
      - ./config/composer/auth.json:/root/.composer/auth.json
      - ./config/ssh:/root/.ssh
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/magento2-php.ini
    env_file:
      - ./env/php.env

  magento2_mysql:
    image: mysql:5.7
    container_name: magento2_mysql
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - magento2_application
    volumes_from:
      - magento2_application
    ports:
      - 3307:3306
    expose:
      - 3306
    env_file:
      - ./env/mysql.env

  magento2_mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025
    ports:
      - 8025:8025

  magento2_redis:
    image: redis
    #    command: redis-server --requirepass magento2
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - ./data/redis:/data

  magento2_elasticsearch:
    image: docker.pp.ua/magento2-elasticsearch:latest
#    build: ./builds-custom/elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data:rw
    expose:
      - 9200
    ports:
      - 9200:9200
      - 9300:9300

#  magento2_rabbitmq:
#    image: rabbitmq
#    ports:
#      - 4369:4369
#      - 5671:5671
#      - 5672:5672
#      - 25672:25672
#    expose:
#      - 4369
#      - 5671
#      - 5672
#      - 25672
#    volumes:
#      - ./data/rabbitmq:/var/lib/rabbitmq
